name: Pyapp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configura ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run testes
      run: |
        coverage run app-teste.py
        coverage report

    - name: Resultados
      run: coverage report
